---
- name: deploy dbheroapp
  hosts: dbheroapp
  tasks:
  - name: get repo sha1
    local_action: command ../get-sha1.sh
    register: sha1
  - name: build
    local_action: command python build.py
  - name: stop currently running
    command: systemctl stop website
    sudo: yes
    ignore_errors: yes
  - name: create systemd file
    copy: src=website.service dest=/lib/systemd/system/website.service owner=root group=root mode=0644
    sudo: yes
  - name: make changes to website.service visible
    command: systemctl daemon-reload
    sudo: yes
  - name: enable the service so that it restarts on reboot
    command: systemctl enable website
    sudo: yes
  - name: create directory for the app
    file: >
      path=/home/dbheroapp/www/app/{{ sha1.stdout }}
      state=directory mode=0755
      owner=dbheroapp group=dbheroapp
  - name: create directory for apps log
    file: >
      path=/home/dbheroapp/www/data/log
      state=directory mode=0755
      owner=dbheroapp group=dbheroapp
  - name: unzip files
    unarchive: src={{ sha1.stdout }}.zip dest=/home/dbheroapp/www/app/{{ sha1.stdout }}
  - name: stat current
    stat: path=/home/dbheroapp/www/app/current
    register: current_stat
  - name: remove old prev directory
    file: path=/home/dbheroapp/www/app/prev state=absent
  - name: rename current to prev
    command: mv current prev
    when: current_stat.stat.exists
    args:
      chdir: /home/dbheroapp/www/app
  - name: symlink sha1 to current
    file: >
      src=/home/dbheroapp/www/app/{{ sha1.stdout }}
      dest=/home/dbheroapp/www/app/current
      state=link
  - name: start it
    command: systemctl start website
    sudo: yes
  - name: delete .zip file
    local_action: command rm {{ sha1.stdout }}.zip
  - name: show status
    command: systemctl status website
    sudo: yes
    register: website_status
  - debug: var=website_status.stdout_lines
