---
- name: initial setup for dbheroapp.com server
  hosts: dbheroapp-initial
  sudo: True
  tasks:
    - name: create a group for the user
      group: name=dbheroapp state=present
    - name: create a user
      user: name=dbheroapp group=dbheroapp groups="sudo" shell=/bin/bash
    - name: make user a sudoer
      lineinfile: dest=/etc/sudoers state=present regexp='^%dbheroapp' line='%dbheroapp ALL=(ALL) NOPASSWD:ALL'
    - name: increase hard file limit
      lineinfile: dest=/etc/security/limits.conf state=present line="dbheroapp hard nofile 375836"
    - name: increase soft file limit
      lineinfile: dest=/etc/security/limits.conf state=present line="dbheroapp soft nofile 375836"
    - name: increse file limit
      lineinfile: dest=/etc/pam.d/common-session state=present line="session required pam_limits.so"
    - name: increse file limit 2
      lineinfile: dest=/etc/pam.d/common-session-noninteractive state=present line="session required pam_limits.so"
    - name: increase shmmax
      lineinfile: dest=/etc/sysctl.conf state=present line="kernel.shmmax=536870912"
    - name: increase shmall
      lineinfile: dest=/etc/sysctl.conf state=present line="kernel.shmall=131072"
    - name: reload sysctl vars
      command: /sbin/sysctl -p
    - name: create users .ssh directory
      file: path=/home/dbheroapp/.ssh state=directory owner=dbheroapp group=dbheroapp mode=0755
    - name: copy ssh key
      copy: src=../dbheroapp_rsa.pub dest=/home/dbheroapp/.ssh/authorized_keys
    - name: configure authorized_keys
      file: path=/home/dbheroapp/.ssh/authorized_keys mode=0644 owner=dbheroapp group=dbheroapp
    - name: install desired software
      apt: name={{ item }} state=latest update_cache=yes cache_valid_time=120
      with_items:
        - unzip
        - tar
        - nginx
    - name: create directory for nginx logs
      file: >
        path=/var/log/nginx/dbheroapp/ state=directory mode=0755
    - name: create directory for nginx certificates
      file: >
        path=/etc/nginx/ssl/ state=directory mode=0755
    - name: copy nginx certificate
      copy: src=dbheroapp.com.chained.crt dest=/etc/nginx/ssl/dbheroapp.com.chained.crt
    - name: copy nginx key
      copy: src=dbheroapp.com.key dest=/etc/nginx/ssl/dbheroapp.com.key
    - name: copy nginx config file
      copy: src=nginx.conf.ssl dest=/etc/nginx/sites-available/dbheroapp
    - name: enable website
      file: >
        dest=/etc/nginx/sites-enabled/dbheroapp
        src=/etc/nginx/sites-available/dbheroapp
        state=link
    - name: restart nginx
      service: name=nginx state=restarted
